# -*- coding: utf-8 -*-
"""m23ma2009Q1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-xNUg7yyYczglb59ixZl1W22eobKnff5
"""

# !pip install wordcloud
# !pip install gensim
from gensim.models import Word2Vec

import os
import re
import string
from wordcloud import WordCloud
import matplotlib.pyplot as plt

folder_path = "."

documents = []

for file in os.listdir(folder_path):
    # yaha folder ke andar jo bhi files hain un par loop run ho raha hai

    if file.endswith(".txt"):
        # only process files with .txt extension

        file_path = os.path.join(folder_path, file)

        with open(file_path, "r", encoding="latin-1") as f:
            text = f.read()   # read the entire text file

            documents.append(text)
            # jo text mila usko documents list me add kar diya

print("Total files loaded:", len(documents))
# print total number of text files loaded

cleaned_docs = []

for text in documents:

    # 1 Remove URLs
    text = re.sub(r'http\S+|www\S+', ' ', text)

    # 2 emove section numbers like 10.2.3 or 1.
    text = re.sub(r'\b\d+(\.\d+)*\b', ' ', text)

    # 3 Remove course codes like MAL7XX0, CSL7XX0
    text = re.sub(r'\b[A-Z]{2,}\d+[A-Z]*\b', ' ', text)

    # 4 Remove content inside square brackets
    text = re.sub(r'\[.*?\]', ' ', text)

    # 5 Remove extra line breaks
    text = re.sub(r'\n+', ' ', text)

    # 6 Remove multiple spaces
    text = re.sub(r'\s+', ' ', text)

    # 7 Strip leading and trailing spaces
    text = text.strip()

    cleaned_docs.append(text)

print("Cleaning Step Completed")
print(cleaned_docs[0][:100000])

cleaned_docs = [doc.lower() for doc in cleaned_docs]
print(cleaned_docs[0][:100000])

final_docs = []

for text in cleaned_docs:

    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))

    final_docs.append(text)

final_docs_alpha = []

for text in final_docs:
    # loop har document/text par chalega jo final_docs list me hai

    text = re.sub(r'[^a-zA-Z\s]', '', text)
    # using regex to remove numbers, punctuation etc.
    # basically sirf alphabets aur spaces ko hi rehne diya hai

    final_docs_alpha.append(text)
    # cleaned text ko new list me add kar diya

doc_number = 0   # change number here

print(final_docs_alpha[doc_number][:1500])

tokenized_docs = []

for text in final_docs_alpha:

    tokens = text.split()

    tokenized_docs.append(tokens)

doc_number = 0   # change number here

print(tokenized_docs[doc_number][:1500])

filtered_docs = []

for tokens in tokenized_docs:

    filtered = [word for word in tokens if len(word) > 1]

    filtered_docs.append(filtered)

corpus = filtered_docs
doc_number = 0   # change number here

print(corpus[doc_number][:1500])

total_documents = len(corpus)
# total number of documents in the corpus

print("Total Documents:", total_documents)

total_tokens = sum(len(doc) for doc in corpus)
# yaha hum sabhi documents ke tokens ko add karke total tokens count kar rahe hain

print("Total Tokens:", total_tokens)

vocab = set()
# set use kiya hai taaki unique words automatically store ho jaye

for doc in corpus:
    vocab.update(doc)
    # har document ke tokens ko vocabulary set me add kar rahe hain

print("Vocabulary Size:", len(vocab))
# final vocabulary size (unique tokens count

combined_text = " ".join(final_docs_alpha)
# saare cleaned documents ko ek single text string me combine kar diya

wordcloud = WordCloud(
    width=1000,
    height=500,
    background_color='white'
).generate(combined_text)
# generate wordcloud using the combined text

# Get top 10 frequent words
top10_words = list(wordcloud.words_.items())[:10]

print("Top 10 Most Frequent Words:")

# Output in required format
output = []

for word, freq in top10_words:
    output.append(f"{word}, {freq}")

print(", ".join(output))

plt.figure(figsize=(15,7))
# create a large figure so the wordcloud looks clear

plt.imshow(wordcloud, interpolation='bilinear')

plt.axis("off")
# axis hide kar diya kyunki image display karni hai

plt.show()

from gensim.parsing.preprocessing import STOPWORDS

filtered_corpus = []

for doc in corpus:
    # loop through each document in the corpus

    filtered_words = [word for word in doc if word not in STOPWORDS]
    # remove stopwords from the document using list comprehension

    filtered_corpus.append(filtered_words)
    # cleaned words ko new list me store kar diya

corpus = filtered_corpus
# ab corpus ko update kar diya with stopword-removed documents

def run_cbow(corpus, dim, window, neg):

    print("\n----------------------------------")
    print("Training CBOW Model")
    print("Embedding Dimension:", dim)   # embedding vector ka size
    print("Window Size:", window)
    print("Negative Samples:", neg)
    print("----------------------------------")

    model = Word2Vec(
        sentences=corpus,
        vector_size=dim,
        window=window,
        negative=neg,
        sg=0,              # sg=0 ka matlab CBOW architecture use ho raha hai
        min_count=3,       # very rare words remove kar diye jate hain
        workers=2,
        epochs=20          # model ko 20 times corpus par train kar rahe hain
    )

    print("Vocabulary Size:", len(model.wv))
    # total unique words jo model ne learn kiye

    if "research" in model.wv:
        # check kar rahe hain ki word vocabulary me present hai ya nahi
        print("Top 5 words similar to 'research':")
        print(model.wv.most_similar("research", topn=5))
        # similar words based on learned embeddings

    return model
    # trained CBOW model return kar diya

# dim = 80
model_80_3_8  = run_cbow(corpus, dim=80,  window=3, neg=8)
model_80_3_15 = run_cbow(corpus, dim=80,  window=3, neg=15)

model_80_5_8  = run_cbow(corpus, dim=80,  window=5, neg=8)
model_80_5_15 = run_cbow(corpus, dim=80,  window=5, neg=15)

model_80_8_8  = run_cbow(corpus, dim=80,  window=8, neg=8)
model_80_8_15 = run_cbow(corpus, dim=80,  window=8, neg=15)


# dim = 150
model_150_3_8  = run_cbow(corpus, dim=150, window=3, neg=8)
model_150_3_15 = run_cbow(corpus, dim=150, window=3, neg=15)

model_150_5_8  = run_cbow(corpus, dim=150, window=5, neg=8)
model_150_5_15 = run_cbow(corpus, dim=150, window=5, neg=15)

model_150_8_8  = run_cbow(corpus, dim=150, window=8, neg=8)
model_150_8_15 = run_cbow(corpus, dim=150, window=8, neg=15)


# dim = 240
model_240_3_8  = run_cbow(corpus, dim=240, window=3, neg=8)
model_240_3_15 = run_cbow(corpus, dim=240, window=3, neg=15)

model_240_5_8  = run_cbow(corpus, dim=240, window=5, neg=8)
model_240_5_15 = run_cbow(corpus, dim=240, window=5, neg=15)

model_240_8_8  = run_cbow(corpus, dim=240, window=8, neg=8)
model_240_8_15 = run_cbow(corpus, dim=240, window=8, neg=15)

def run_skipgram(corpus, dim, window, neg):

    print("\n----------------------------------")
    print("Training Skip-gram Model")
    print("Embedding Dimension:", dim)   # embedding vector ka size
    print("Window Size:", window)
    print("Negative Samples:", neg)
    print("----------------------------------")

    model = Word2Vec(
        sentences=corpus,
        vector_size=dim,
        window=window,
        negative=neg,
        sg=1,          # sg=1 means Skip-gram architecture use ho raha hai
        min_count=3,   # very rare words ko ignore kar diya jata hai
        workers=2,
        epochs=20      # model ko multiple passes me train kar rahe hain
    )

    print("Vocabulary Size:", len(model.wv))
    # total unique words jo model ne learn kiye

    if "research" in model.wv:
        # check kar rahe hain ki 'research' word vocabulary me hai ya nahi
        print("Top 5 words similar to 'research':")
        print(model.wv.most_similar("research", topn=5))
        # model ke according sabse similar words nikal rahe hain

    return model

# dim = 80
skip_80_3_8  = run_skipgram(corpus, dim=80,  window=3, neg=8)
skip_80_3_15 = run_skipgram(corpus, dim=80,  window=3, neg=15)

skip_80_5_8  = run_skipgram(corpus, dim=80,  window=5, neg=8)
skip_80_5_15 = run_skipgram(corpus, dim=80,  window=5, neg=15)

skip_80_8_8  = run_skipgram(corpus, dim=80,  window=8, neg=8)
skip_80_8_15 = run_skipgram(corpus, dim=80,  window=8, neg=15)


# dim = 150
skip_150_3_8  = run_skipgram(corpus, dim=150, window=3, neg=8)
skip_150_3_15 = run_skipgram(corpus, dim=150, window=3, neg=15)

skip_150_5_8  = run_skipgram(corpus, dim=150, window=5, neg=8)
skip_150_5_15 = run_skipgram(corpus, dim=150, window=5, neg=15)

skip_150_8_8  = run_skipgram(corpus, dim=150, window=8, neg=8)
skip_150_8_15 = run_skipgram(corpus, dim=150, window=8, neg=15)


# dim = 240
skip_240_3_8  = run_skipgram(corpus, dim=240, window=3, neg=8)
skip_240_3_15 = run_skipgram(corpus, dim=240, window=3, neg=15)

skip_240_5_8  = run_skipgram(corpus, dim=240, window=5, neg=8)
skip_240_5_15 = run_skipgram(corpus, dim=240, window=5, neg=15)

skip_240_8_8  = run_skipgram(corpus, dim=240, window=8, neg=8)
skip_240_8_15 = run_skipgram(corpus, dim=240, window=8, neg=15)

import numpy as np

# ----------- Train Best Model -----------
best_model = run_skipgram(corpus, dim=150, window=3, neg=8)
# Skip-gram model ko train kar rahe hain with selected hyperparameters

vec = best_model.wv['lecture']
print("lecture -", ", ".join(map(str, vec)))


# ----------- Manual Cosine Function -----------
def cosine_similarity(v1, v2):

    dot_product = np.dot(v1, v2)
    # do vectors ka dot product calculate kar rahe hain

    norm_v1 = np.linalg.norm(v1)
    norm_v2 = np.linalg.norm(v2)
    # yaha dono vectors ka magnitude (length) nikal rahe hain

    return dot_product / (norm_v1 * norm_v2)
    # cosine similarity formula apply kiya


# Function to Find Top 5 Neighbors
def get_top5_neighbors(word, model):

    if word not in model.wv:
        print(f"{word} not in vocabulary")
        return

    target_vector = model.wv[word]
    similarities = []
    # is list me sab words ki similarity store hogi

    for other_word in model.wv.index_to_key:
        if other_word != word:
            other_vector = model.wv[other_word]

            sim = cosine_similarity(target_vector, other_vector)
            # manually cosine similarity compute kar rahe hain

            similarities.append((other_word, sim))
            # word aur uski similarity value store kar di

    # Sort by similarity descending
    similarities = sorted(similarities, key=lambda x: x[1], reverse=True)
    # highest similarity wale words upar aa jayenge

    print(f"\nTop 5 nearest neighbors for '{word}':")

    for w, s in similarities[:5]:
        print(w, round(s, 4))
        # top 5 most similar words print kar rahe hain


# Run for Required Words
words_to_check = ["research", "student", "phd", "exam"]
# ye wo words hain jinke neighbors check karne hain

for w in words_to_check:
    get_top5_neighbors(w, best_model)
    # har word ke liye function call karke similar words nikal rahe hain

#  Analogy Function
def analogy(word_a, word_b, word_c, model):

    if word_a not in model.wv or word_b not in model.wv or word_c not in model.wv:
        print("One of the words not in vocabulary")
        return
        # agar koi word model ki vocabulary me nahi hai to function stop ho jayega

    vec_a = model.wv[word_a]
    vec_b = model.wv[word_b]
    vec_c = model.wv[word_c]
    # yaha teenon words ke embedding vectors nikal rahe hain

    # vB - vA + vC
    target_vector = vec_b - vec_a + vec_c
    # analogy rule apply kiya (classic word embedding trick)

    similarities = []

    for word in model.wv.index_to_key:
        # model ki vocabulary ke sabhi words par loop
        if word not in [word_a, word_b, word_c]:

            vec = model.wv[word]
            sim = cosine_similarity(target_vector, vec)
            # target vector aur current word ke vector ke beech similarity calculate

            similarities.append((word, sim))
            # word aur similarity value list me store kar di

    similarities = sorted(similarities, key=lambda x: x[1], reverse=True)
    # highest similarity wale words top par aa jayenge

    print(f"\nAnalogy: {word_a} : {word_b} :: {word_c} : ?")

    for w, s in similarities[:5]:
        print(w, round(s, 4))
        # top 5 most similar candidate words print kar rahe hain


# Three Analogy Experiments

# Experiment 1
analogy("research", "journals", "student", best_model)

# Experiment 2
analogy("phd", "doctor", "masters", best_model)

# Experiment 3
analogy("research", "collaborations", "teaching", best_model)
# different word relationships test kar rahe hain using the trained model

import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
# libraries import ki hain for numerical work, plotting, and PCA

# Words from different semantic groups
words = [
    # Research related
    "research", "journals", "publication", "innovation", "collaborations",
    "interests", "projects", "foundation", "excellence", "grant",

    # Student / academic
    "student", "students", "phd", "masters", "course",
    "semester", "registration", "eligible", "registered", "candidate",

    # Teaching / learning
    "teaching", "learning", "lecture", "tutorial",
    "workshops", "training", "academic",

    # Research environment
    "laboratories", "thematic", "analysis", "data", "model",

    # Institution / organization
    "university", "faculty", "national", "centre", "government"
]

# Extract vectors
vectors = []
valid_words = []   # yaha sirf wo words store honge jo model ki vocabulary me milenge

for word in words:
    if word in best_model.wv:
        vectors.append(best_model.wv[word])
        valid_words.append(word)
        # agar word vocabulary me hai to uska embedding vector store kar lete hain

vectors = np.array(vectors)
# list ko numpy array me convert kiya taaki PCA apply kar sake

# Apply PCA
pca = PCA(n_components=2)
reduced_vectors = pca.fit_transform(vectors)
# high dimensional embeddings ko 2D me reduce kar rahe hain for visualization

# Plot
plt.figure(figsize=(8,6))
plt.scatter(reduced_vectors[:,0], reduced_vectors[:,1])
# 2D scatter plot of the reduced vectors

for i, word in enumerate(valid_words):
    plt.annotate(word, (reduced_vectors[i,0], reduced_vectors[i,1]))
    # har point ke paas corresponding word label show kar rahe hain

plt.title("PCA Projection of Word Embeddings")
plt.xlabel("PC1")
plt.ylabel("PC2")

plt.show()
# final plot display ho jayega

import numpy as np
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE
# required libraries import ki hain (numerical operations, plotting, and t-SNE)

# Words from different semantic groups
words = [
    # Research cluster
    "research", "journals", "publication", "innovation", "collaborations",
    "interests", "projects", "foundation", "excellence", "grant",

    # Student / academic cluster
    "student", "students", "phd", "masters", "course",
    "semester", "registration", "registered", "eligible", "candidate",

    # Teaching / learning cluster
    "teaching", "learning", "lecture", "tutorial",
    "workshops", "training", "academic",

    # Research environment
    "laboratories", "analysis", "data", "model",
    "thematic", "simulation",

    # Institution / organization
    "university", "faculty", "national", "centre", "government"
]

# Extract vectors
vectors = []
valid_words = []  # sirf wo words store honge jo model ki vocabulary me present hain

for word in words:
    if word in best_model.wv:
        vectors.append(best_model.wv[word])
        valid_words.append(word)
        # agar word vocabulary me mil gaya to uska embedding vector store kar liya

vectors = np.array(vectors)
# list ko numpy array me convert kiya taaki t-SNE apply kar sake

# Apply t-SNE
tsne = TSNE(n_components=2, perplexity=5, random_state=42)
# t-SNE high dimensional vectors ko 2D space me project karta hai

reduced_vectors = tsne.fit_transform(vectors)

# Plot
plt.figure(figsize=(8,6))
plt.scatter(reduced_vectors[:,0], reduced_vectors[:,1])
# scatter plot bana rahe hain to visualize word embeddings

for i, word in enumerate(valid_words):
    plt.annotate(word, (reduced_vectors[i,0], reduced_vectors[i,1]))
    # har point ke paas corresponding word label show kar diya

plt.title("t-SNE Projection of Word Embeddings")
plt.xlabel("Dim 1")
plt.ylabel("Dim 2")

plt.show()
# final visualization display ho jayega
