# -*- coding: utf-8 -*-
"""m23ma2009Q2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UpPL-V6NeNROvN-Bt4Be_CBqJip2n4aN
"""

import numpy as np
# numpy use kar rahe hain vector operations aur arrays ke liye

# 1 Load Data
with open("Training_name.txt", "r", encoding="utf-8") as f:
    names = f.read().splitlines()
    # file se saare names read karke list me store kar liye

# 2 Lowercase (recommended)
names = [name.lower() for name in names]
# sab names ko lowercase me convert kar diya for consistency

# 3 Build Vocabulary
all_text = "".join(names)
# saare names ko join karke ek single string bana di

unique_chars = sorted(list(set(all_text)))
# text me jitne unique characters hain unko extract kar liya

# Add special tokens
unique_chars = ['<SOS>', '<EOS>'] + unique_chars
# start-of-sequence aur end-of-sequence tokens add kiye

vocab_size = len(unique_chars)
# total vocabulary size calculate kiya

# 4 Create mappings
char2idx = {}
idx2char = {}

for i, ch in enumerate(unique_chars):
    char2idx[ch] = i
    idx2char[i] = ch
    # character ↔ index mapping bana rahe hain (encoding/decoding ke liye)

# 5 One-hot encoding function
def one_hot(index, vocab_size):
    vec = np.zeros((vocab_size, 1))
    vec[index] = 1
    # given index ko one-hot vector me convert kar diya
    return vec

# 6 Convert names to input-target sequences
data = []

for name in names:
    seq = ['<SOS>'] + list(name) + ['<EOS>']
    # sequence ke start aur end me special tokens add kiye

    indices = [char2idx[ch] for ch in seq]
    # characters ko unke corresponding index me convert kar diya

    inputs = indices[:-1]   # all except last
    targets = indices[1:]   # all except first
    # basically next character prediction ke liye input-target pair bana rahe hain

    data.append((inputs, targets))
    # har name ka training pair dataset me add kar diya

print("Vocab size:", vocab_size)
print("Example name:", names[0])

print("Encoded input:", data[0][0])
print("Encoded target:", data[0][1])
# example dekhne ke liye first name ka encoded version print kar rahe hain

for i in range(5):
    print("Original name:", names[i])
    print("Input indices:", data[i][0])
    print("Target indices:", data[i][1])
    print()

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np


# Hyperparameters

embedding_dim = 32
hidden_size = 96
learning_rate = 0.002
epochs = 20
patience = 3

V = vocab_size
# Model

class NameRNN(nn.Module):

    def __init__(self, vocab_size, embedding_dim, hidden_size):
        super(NameRNN, self).__init__()

        self.embedding = nn.Embedding(vocab_size, embedding_dim)

        self.rnn = nn.RNN(
            embedding_dim,
            hidden_size,
            batch_first=True
        )

        self.dropout = nn.Dropout(0.3)

        self.fc = nn.Linear(hidden_size, vocab_size)

    def forward(self, x, hidden):

        x = self.embedding(x)

        out, hidden = self.rnn(x, hidden)

        out = self.dropout(out)

        out = self.fc(out)

        return out, hidden


model = NameRNN(V, embedding_dim, hidden_size)


criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(
    model.parameters(),
    lr=learning_rate,
    weight_decay=1e-5
)


# Train / Validation Split


split = int(0.9 * len(data))

train_data = data[:split]
val_data = data[split:]



# Early Stopping Variables


best_val = float("inf")
patience_counter = 0



# Training

for epoch in range(epochs):

    model.train()

    train_loss = 0
    char_count = 0

    for inputs, targets in train_data:

        x = torch.tensor(inputs).unsqueeze(0)
        y = torch.tensor(targets)

        hidden = torch.zeros(1,1,hidden_size)

        optimizer.zero_grad()

        output, hidden = model(x, hidden)

        output = output.squeeze(0)

        loss = criterion(output, y)

        loss.backward()

        torch.nn.utils.clip_grad_norm_(model.parameters(), 5)

        optimizer.step()

        train_loss += loss.item()*len(inputs)
        char_count += len(inputs)

    train_loss = train_loss / char_count
    # Validation


    model.eval()

    val_loss = 0
    val_chars = 0

    with torch.no_grad():

        for inputs, targets in val_data:

            x = torch.tensor(inputs).unsqueeze(0)
            y = torch.tensor(targets)

            hidden = torch.zeros(1,1,hidden_size)

            output, hidden = model(x, hidden)

            output = output.squeeze(0)

            loss = criterion(output, y)

            val_loss += loss.item()*len(inputs)
            val_chars += len(inputs)

    val_loss = val_loss / val_chars

    print(f"Epoch {epoch+1}  Train Loss: {train_loss:.4f}  Validation Loss: {val_loss:.4f}")


    # Early Stopping

    if val_loss < best_val:

        best_val = val_loss
        patience_counter = 0

    else:

        patience_counter += 1

        if patience_counter >= patience:

            print("Early stopping triggered")
            break

import torch
import torch.nn.functional as F
import numpy as np

def generate_name(start_char="a", max_length=20, temperature=0.5, k=3):

    model.eval()

    name = start_char
    char = start_char

    hidden = torch.zeros(1,1,hidden_size)

    for i in range(max_length):

        idx = torch.tensor([[char2idx[char]]])

        # forward pass
        output, hidden = model(idx, hidden)

        logits = output[0,0] / max(temperature,1e-6)

        probs = F.softmax(logits, dim=0).detach().numpy()

        # safe top-k
        k_eff = min(k,len(probs))
        top_k_idx = np.argsort(probs)[-k_eff:]

        top_k_probs = probs[top_k_idx]
        top_k_probs = top_k_probs / np.sum(top_k_probs)

        sampled_idx = np.random.choice(top_k_idx,p=top_k_probs)

        char = idx2char[sampled_idx]

        if char == "<EOS>" and len(name) > 3:
            break

        if char != "<EOS>":
            name += char

    return name


# generate samples
for i in range(20):
    print(generate_name("b"))

import torch
import torch.nn as nn
import torch.optim as optim
import random

# Reproducibility

torch.manual_seed(42)
random.seed(42)

# Device

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


# Hyperparameters


embedding_dim = 32
hidden_size = 128
learning_rate = 0.002
epochs = 25
patience = 4

V = vocab_size


# Shuffle before split

random.shuffle(data)

split = int(0.9 * len(data))
train_data = data[:split]
val_data = data[split:]

# Model


class NameLSTM(nn.Module):

    def __init__(self, vocab_size, embedding_dim, hidden_size):
        super().__init__()

        self.embedding = nn.Embedding(vocab_size, embedding_dim)

        self.lstm = nn.LSTM(
            embedding_dim,
            hidden_size,
            batch_first=True
        )

        self.dropout = nn.Dropout(0.3)

        self.fc = nn.Linear(hidden_size, vocab_size)

    def forward(self, x, hidden):

        x = self.embedding(x)

        out, hidden = self.lstm(x, hidden)

        out = self.dropout(out)

        out = self.fc(out)

        return out, hidden


model = NameLSTM(V, embedding_dim, hidden_size).to(device)

criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(
    model.parameters(),
    lr=learning_rate,
    weight_decay=1e-5
)

# Early stopping

best_val = float("inf")
patience_counter = 0
# Training


for epoch in range(epochs):

    model.train()

    train_loss = 0
    char_count = 0

    for inputs, targets in train_data:

        x = torch.tensor(inputs, dtype=torch.long).unsqueeze(0).to(device)
        y = torch.tensor(targets, dtype=torch.long).to(device)

        hidden = (
            torch.zeros(1,1,hidden_size).to(device),
            torch.zeros(1,1,hidden_size).to(device)
        )

        optimizer.zero_grad()

        output, hidden = model(x, hidden)

        output = output.squeeze(0)

        loss = criterion(output, y)

        loss.backward()

        torch.nn.utils.clip_grad_norm_(model.parameters(), 5)

        optimizer.step()

        train_loss += loss.item() * len(inputs)
        char_count += len(inputs)

    train_loss = train_loss / char_count


    # Validation


    model.eval()

    val_loss = 0
    val_chars = 0

    with torch.no_grad():

        for inputs, targets in val_data:

            x = torch.tensor(inputs, dtype=torch.long).unsqueeze(0).to(device)
            y = torch.tensor(targets, dtype=torch.long).to(device)

            hidden = (
                torch.zeros(1,1,hidden_size).to(device),
                torch.zeros(1,1,hidden_size).to(device)
            )

            output, hidden = model(x, hidden)

            output = output.squeeze(0)

            loss = criterion(output, y)

            val_loss += loss.item() * len(inputs)
            val_chars += len(inputs)

    val_loss = val_loss / val_chars

    print(f"Epoch {epoch+1}  Train Loss: {train_loss:.4f}  Validation Loss: {val_loss:.4f}")

    # Early stopping


    if val_loss < best_val:

        best_val = val_loss
        patience_counter = 0

        torch.save(model.state_dict(), "best_lstm_model.pt")

    else:

        patience_counter += 1

        if patience_counter >= patience:
            print("Early stopping triggered")
            break


model.load_state_dict(torch.load("best_lstm_model.pt"))

import torch
import torch.nn.functional as F
import numpy as np

def generate_name_blstm(start_char="a",
                        max_length=12,
                        min_length=3,
                        temperature=0.9,
                        k=5):

    model.eval()

    name = start_char
    char = start_char

    hidden = (
        torch.zeros(1,1,hidden_size).to(device),
        torch.zeros(1,1,hidden_size).to(device)
    )

    for _ in range(max_length):

        x = torch.tensor([[char2idx[char]]], dtype=torch.long).to(device)

        with torch.no_grad():
            output, hidden = model(x, hidden)

        logits = output[0,0] / max(temperature,1e-6)

        probs = F.softmax(logits, dim=0).cpu().numpy()

        # prevent early EOS
        if len(name) < min_length:
            probs[char2idx["<EOS>"]] = 0
            probs = probs / np.sum(probs)

        # top-k sampling
        k_eff = min(k, len(probs))
        top_k_idx = np.argsort(probs)[-k_eff:]

        top_k_probs = probs[top_k_idx]
        top_k_probs /= np.sum(top_k_probs)

        sampled_idx = np.random.choice(top_k_idx, p=top_k_probs)

        char = idx2char[sampled_idx]

        if char == "<EOS>":
            break

        name += char

    return name
    # generate samples
# for i in range(20):
#     print(generate_name("a"))

for i in range(20):
    print(generate_name_blstm("a"))


import numpy as np

# Hyperparameters

hidden_size = 128
learning_rate = 0.003
epochs = 20

H = hidden_size
V = vocab_size


# Better Weight Initialization

Wxh = np.random.randn(V,H)/np.sqrt(V)
Whh = np.random.randn(H,H)/np.sqrt(H)
bh  = np.zeros((1,H))

Why = np.random.randn(2*H,V)/np.sqrt(2*H)
by  = np.zeros((1,V))


# Functions

def softmax(x):
    e = np.exp(x-np.max(x))
    return e/np.sum(e)

def dtanh(x):
    return 1-x*x


# Train / Validation Split

split = int(0.9*len(data))
train_data = data[:split]
val_data = data[split:]


best_val = float("inf")
patience = 3
patience_counter = 0


# Training

for epoch in range(epochs):

    np.random.shuffle(train_data)

    train_loss = 0
    char_count = 0

    for inputs,targets in train_data:

        T = len(inputs)

        xs = []
        hs = np.zeros((T,H))

        h_prev = np.zeros((1,H))


        # RNN Forward

        for t in range(T):

            x = np.zeros((1,V))
            x[0][inputs[t]] = 1

            xs.append(x)

            h = np.tanh(x@Wxh + h_prev@Whh + bh)

            hs[t] = h
            h_prev = h


        # Attention + Output

        p_list = []
        weight_list = []
        concat_list = []

        for t in range(T):

            query = hs[t]

            scores = hs @ query.reshape(H,1)

            weights = softmax(scores)

            context = weights.T @ hs

            h_concat = np.concatenate((query,context.flatten())).reshape(1,2*H)

            y = h_concat@Why + by
            p = softmax(y)

            train_loss += -np.log(p[0][targets[t]]+1e-8)
            char_count += 1

            p_list.append(p)
            weight_list.append(weights)
            concat_list.append(h_concat)


        # Gradients

        dWxh = np.zeros_like(Wxh)
        dWhh = np.zeros_like(Whh)
        dbh  = np.zeros_like(bh)

        dWhy = np.zeros_like(Why)
        dby  = np.zeros_like(by)

        dh = np.zeros((T,H))


        # Backprop through Attention

        for t in reversed(range(T)):

            p = p_list[t]

            dy = p.copy()
            dy[0][targets[t]] -= 1

            h_concat = concat_list[t]

            dWhy += h_concat.T @ dy
            dby  += dy

            dh_concat = dy @ Why.T

            dh_query = dh_concat[:,:H].flatten()
            dcontext = dh_concat[:,H:].flatten()

            dh[t] += dh_query

            weights = weight_list[t]

            for j in range(T):
                dh[j] += weights[j] * dcontext


        # Backprop through RNN

        dh_next = np.zeros((1,H))

        for t in reversed(range(T)):

            h = hs[t].reshape(1,H)

            dh_total = dh[t].reshape(1,H) + dh_next

            dt = dh_total * dtanh(h)

            x = xs[t]

            h_prev = hs[t-1].reshape(1,H) if t>0 else np.zeros((1,H))

            dWxh += x.T @ dt
            dWhh += h_prev.T @ dt
            dbh  += dt

            dh_next = dt @ Whh.T


        # Gradient Clipping

        for dparam in [dWxh,dWhh,dbh,dWhy,dby]:
            np.clip(dparam,-5,5,out=dparam)


        # Parameter Update

        Wxh -= learning_rate*dWxh
        Whh -= learning_rate*dWhh
        bh  -= learning_rate*dbh

        Why -= learning_rate*dWhy
        by  -= learning_rate*dby


    # Validation

    val_loss = 0
    val_char_count = 0

    for inputs,targets in val_data:

        T = len(inputs)

        hs = np.zeros((T,H))

        h_prev = np.zeros((1,H))

        for t in range(T):

            x = np.zeros((1,V))
            x[0][inputs[t]] = 1

            h = np.tanh(x@Wxh + h_prev@Whh + bh)

            hs[t] = h
            h_prev = h


        for t in range(T):

            scores = hs @ hs[t].reshape(H,1)

            weights = softmax(scores)

            context = weights.T @ hs

            h_concat = np.concatenate((hs[t],context.flatten())).reshape(1,2*H)

            y = h_concat @ Why + by

            p = softmax(y)

            val_loss += -np.log(p[0][targets[t]]+1e-8)
            val_char_count += 1


    val_loss = val_loss/val_char_count
    train_loss = train_loss/char_count

    print(f"Epoch {epoch+1}  Train Loss: {train_loss:.4f}  Validation Loss: {val_loss:.4f}")


    # Early Stopping

    if val_loss < best_val:
        best_val = val_loss
        patience_counter = 0
    else:
        patience_counter += 1

    if patience_counter >= patience:
        print("Early stopping triggered")
        break

def generate_name_attention(start_char="a", max_length=15, min_length=3, temperature=0.6, k=4):

    name = start_char
    char = start_char

    h_prev = np.zeros((1,H))
    hs = []

    for step in range(max_length):

        # one-hot input
        x = np.zeros((1,V))
        x[0][char2idx[char]] = 1

        # RNN step
        h = np.tanh(x @ Wxh + h_prev @ Whh + bh)

        hs.append(h.flatten())
        h_prev = h

        hs_matrix = np.array(hs)

        # Attention
        query = h.flatten()

        scores = hs_matrix @ query.reshape(H,1)

        weights = np.exp(scores - np.max(scores))
        weights = weights / np.sum(weights)

        context = weights.T @ hs_matrix

        #  Output
        h_concat = np.concatenate((query,context.flatten())).reshape(1,2*H)

        y = h_concat @ Why + by

        # safe temperature
        temperature = max(temperature,1e-6)
        y = y / temperature

        p = np.exp(y - np.max(y))
        p = p / np.sum(p)
        p = p.flatten()

        # prevent EOS too early
        if len(name) < min_length:
            eos_idx = char2idx["<EOS>"]
            p[eos_idx] = 0
            p = p / np.sum(p)

        # safe top-k
        k_eff = min(k,len(p))
        top_k_idx = np.argsort(p)[-k_eff:]

        top_k_probs = p[top_k_idx]
        top_k_probs = top_k_probs / np.sum(top_k_probs)

        idx = np.random.choice(top_k_idx,p=top_k_probs)

        char = idx2char[idx]

        if char == "<EOS>":
            break

        name += char

    return name


# generate names
for i in range(20):
    print(generate_name_attention("a"))

# RNN Novelty Rate + Diversity

N = 1000
# total kitne names generate karne hain evaluation ke liye

# generate names using existing function

# generated_names = [generate_name("a") for _ in range(N)]
generated_names = [generate_name_blstm("a") for _ in range(N)]

# trained RNN model se 1000 names generate kar rahe hain

#  training names extract
train_set = set(
    "".join(idx2char[i] for i in inputs if idx2char[i] != "<EOS>")
    for inputs, _ in train_data
)
# training dataset ke original names ko reconstruct karke set me store kiya

#  novelty rate
novelty_rate = sum(name not in train_set for name in generated_names) / N
# check kar rahe hain kitne generated names training set me pehle se nahi the

#  diversity
diversity = len(set(generated_names)) / N
# unique generated names ka ratio (model kitna variety produce kar raha hai)

print("\n RNN MODEL METRICS ")
print("Novelty Rate:", novelty_rate)
print("Diversity:", diversity)
# final evaluation metrics print kar diye

# ===== BLSTM MODEL METRICS =====

N = 1000

# Generate names

generated_names = []

for _ in range(N):

    name = generate_name_blstm("a")

    # remove EOS if present
    name = name.replace("<EOS>", "")

    # normalize
    name = name.strip().lower()

    if len(name) > 0:
        generated_names.append(name)

# Training names set

train_set = set()

for inputs, _ in train_data:

    name = "".join(idx2char[i] for i in inputs if idx2char[i] != "<EOS>")

    name = name.strip().lower()

    train_set.add(name)

# Novelty Rate

novel_count = sum(name not in train_set for name in generated_names)

novelty_rate = novel_count / len(generated_names)

# Diversity

diversity = len(set(generated_names)) / len(generated_names)

# Print metrics

print("\n BLSTM MODEL METRICS ")

print("Generated names:", len(generated_names))

print("Novelty Rate:", round(novelty_rate,4))

print("Diversity:", round(diversity,4))

#  RNN + ATTENTION MODEL METRICS

N = 1000
# evaluation ke liye 1000 names generate karenge

# generate names using RNN + Attention
generated_names = [generate_name_attention("a") for _ in range(N)]
# trained Attention based model se names generate ho rahe hain

# training names set
train_set = set(
    "".join(idx2char[i] for i in inputs if idx2char[i] != "<EOS>")
    for inputs, _ in train_data
)
# training dataset ke names ko wapas reconstruct karke set me store kiya

# Novelty Rate
novelty_rate = sum(name not in train_set for name in generated_names) / N
# check karte hain kitne generated names training set me pehle se nahi the

# Diversity
diversity = len(set(generated_names)) / N
# unique generated names ka ratio — model kitni variety create kar raha hai

print("\n RNN + ATTENTION MODEL METRICS ")
print("Novelty Rate:", novelty_rate)
print("Diversity:", diversity)
# final metrics print kar rahe hain